---
- name: Create MetalLB namespace
  k8s:
    src: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/namespace.yaml"
    state: present

- name: Install MetalLB
  k8s:
    src: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/metallb.yaml"
    state: present

- name: Config MetalLB
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - {{ addresses }}
    state: present
