---
- name: Disable SELinux
  selinux:
    state: disabled

- name: Set firewall rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 6443/tcp
    - 8472/udp
    - 10250/tcp

- name: Download k3s binary
  get_url:
    url: "https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755

- name: Copy k3s service file
  register: k3s_service
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0755

- name: Enable k3s service
  systemd:
    name: k3s
    state: restarted
    enabled: yes
    daemon_reload: yes
