---
- name: Disable SELinux
  selinux:
    state: disabled

- name: Download k3s binary
  get_url:
    url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755

- name: Copy k3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable k3s service
  systemd:
    name: k3s
    state: started
    enabled: yes
    daemon_reload: yes
